//
//  MirageSupportLogMessages.swift
//  MirageWire
//
//  Created by Ethan Lipnik on 6/5/26.
//

import Foundation

/// Requests a zipped support log archive from the connected host.
package struct HostSupportLogArchiveRequestMessage: Codable {
    /// Client-generated request identifier echoed by the host response and Loom transfer metadata.
    package let requestID: UUID

    package init(requestID: UUID) {
        self.requestID = requestID
    }
}

/// Describes the host support log archive transfer or export failure.
package struct HostSupportLogArchiveMessage: Codable {
    /// Request identifier generated by the client and echoed by the host.
    package let requestID: UUID?
    /// Suggested archive filename, including extension.
    package let fileName: String?
    /// Human-readable failure reason when archive creation was unsuccessful.
    package let errorMessage: String?

    package init(
        requestID: UUID? = nil,
        fileName: String? = nil,
        errorMessage: String? = nil
    ) {
        self.requestID = requestID
        self.fileName = fileName
        self.errorMessage = errorMessage
    }
}
