//
//  MirageClientMetricsSnapshot+Initialization.swift
//  MirageDiagnostics
//
//  Created by Ethan Lipnik on 6/5/26.
//

import MirageMedia

public extension MirageClientMetricsSnapshot {
    /// Creates a metrics snapshot with client presentation data and optional host telemetry.
    init(
        decodedFPS: Double = 0,
        receivedFPS: Double = 0,
        clientReceivedWorstGapMs: Double = 0,
        clientReceivedFrameIntervalP95Ms: Double = 0,
        clientReceivedFrameIntervalP99Ms: Double = 0,
        clientReceiverIngressJitterP95Ms: Double = 0,
        clientReceiverIngressJitterP99Ms: Double = 0,
        clientDisplayTickFPS: Double = 0,
        clientSubmitAttemptFPS: Double = 0,
        clientLayerAcceptedFPS: Double = 0,
        clientPresentedFPS: Double = 0,
        submittedFPS: Double = 0,
        uniqueSubmittedFPS: Double = 0,
        pendingFrameCount: Int = 0,
        clientPendingFrameAgeMs: Double = 0,
        clientSmoothestDisplayDebtMs: Double = 0,
        clientSmoothestDisplayDebtCapMs: Double = 0,
        clientSmoothestTargetDelayMs: Double = 0,
        clientSmoothestUnderflowCount: UInt64 = 0,
        clientOverwrittenPendingFrames: UInt64 = 0,
        clientSmoothestQueueDrops: UInt64 = 0,
        clientSmoothestDisplayDebtDrops: UInt64 = 0,
        clientSmoothestFifoResetCount: UInt64 = 0,
        clientSmoothestDepthDrops: UInt64 = 0,
        clientSmoothestAgeDrops: UInt64 = 0,
        clientSmoothestDropsUnder100ms: UInt64 = 0,
        clientSmoothestDroppedFrameAgeMaxMs: Double = 0,
        clientLateFrameDrops: UInt64 = 0,
        clientDisplayLayerNotReadyCount: UInt64 = 0,
        clientPendingFrameNotReadyDisplayTickCount: UInt64 = 0,
        clientRepeatedFrameCount: UInt64 = 0,
        clientMissedVSyncCount: UInt64 = 0,
        clientDisplayTickIntervalP95Ms: Double = 0,
        clientDisplayTickIntervalP99Ms: Double = 0,
        clientPlayoutDelayFrames: Int = 0,
        clientPresentationStallCount: UInt64 = 0,
        clientWorstPresentationGapMs: Double = 0,
        clientFrameIntervalP95Ms: Double = 0,
        clientFrameIntervalP99Ms: Double = 0,
        decodeHealthy: Bool = true,
        clientDroppedFrames: UInt64 = 0,
        clientReassemblerPendingFrameCount: Int = 0,
        clientReassemblerPendingKeyframeCount: Int = 0,
        clientReassemblerPendingBytes: Int = 0,
        clientFrameBufferPoolRetainedBytes: Int = 0,
        clientReassemblerBudgetEvictions: UInt64 = 0,
        clientReassemblerIncompleteFrameTimeouts: UInt64 = 0,
        clientReassemblerIncompleteFrameNoProgressTimeouts: UInt64 = 0,
        clientReassemblerIncompleteFrameLifetimeTimeouts: UInt64 = 0,
        clientReassemblerMissingFragmentTimeouts: UInt64 = 0,
        clientReassemblerForwardGapTimeouts: UInt64 = 0,
        clientFrameCompletionLatencyP50Ms: Double = 0,
        clientFrameCompletionLatencyP95Ms: Double = 0,
        clientFrameCompletionLatencyMaxMs: Double = 0,
        clientKeyframeCompletionLatencyP50Ms: Double = 0,
        clientKeyframeCompletionLatencyP95Ms: Double = 0,
        clientKeyframeCompletionLatencyMaxMs: Double = 0,
        clientPFrameCompletionLatencyP50Ms: Double = 0,
        clientPFrameCompletionLatencyP95Ms: Double = 0,
        clientPFrameCompletionLatencyMaxMs: Double = 0,
        clientLatePFrameCompletionCount: UInt64 = 0,
        clientReassemblerFECRecoveredFragmentCount: UInt64 = 0,
        hostEncodedFPS: Double = 0,
        hostIdleFPS: Double = 0,
        hostDroppedFrames: UInt64 = 0,
        hostActiveQuality: Double = 0,
        hostLatestAppliedFrameQuality: Double? = nil,
        hostLatestAppliedFrameBitrateTargetBps: Int? = nil,
        hostLatestAppliedFrameSenderPacingBps: Int? = nil,
        hostLatestAppliedFrameIntent: String? = nil,
        hostLatestAppliedFrameRate: Int? = nil,
        hostTargetFrameRate: Int = 0,
        hostEnteredBitrate: Int? = nil,
        hostCurrentBitrate: Int? = nil,
        hostEncoderRequestedBitrateBps: Int? = nil,
        hostEncoderActualBitrateBps: Int? = nil,
        hostEncoderActualWindowMs: Int? = nil,
        hostEncodedFrameBytesP50: Int? = nil,
        hostEncodedFrameBytesP95: Int? = nil,
        hostEncodedFrameBytesP99: Int? = nil,
        hostEncodedKeyframeBytesP50: Int? = nil,
        hostEncodedKeyframeBytesP95: Int? = nil,
        hostEncodedKeyframeBytesP99: Int? = nil,
        hostEncoderRateControlStrategy: MirageMedia.MirageEncoderRateControlStrategy? = nil,
        hostEncoderRateLimitBytes: Int? = nil,
        hostEncoderRateLimitWindowMs: Int? = nil,
        hostEffectiveStreamScale: Double? = nil,
        hostAdaptiveStreamScaleReason: String? = nil,
        hostEncoderRetuneValidationResult: String? = nil,
        hostEncoderKeyframeForRetuneCount: UInt64? = nil,
        hostEncoderSessionRecreationCount: UInt64? = nil,
        hostRequestedTargetBitrate: Int? = nil,
        hostBitrateAdaptationCeiling: Int? = nil,
        hostStartupBitrate: Int? = nil,
        hostRealtimeBitrateCeiling: Int? = nil,
        hostRealtimePressureState: String? = nil,
        hostRealtimeControlRevision: Int? = nil,
        hostAdaptiveGovernorRevision: Int? = nil,
        hostAdaptiveGovernorDecisionID: UInt64? = nil,
        hostAdaptiveGovernorState: String? = nil,
        hostAdaptiveGovernorEvidenceClass: String? = nil,
        hostAdaptiveGovernorCause: String? = nil,
        hostAdaptiveGovernorSelectedLever: String? = nil,
        hostAdaptiveGovernorBlockedLeverReason: String? = nil,
        hostAdaptiveGovernorEvidenceSummary: String? = nil,
        hostRealtimePressureReason: String? = nil,
        hostRealtimeDeliveryMode: String? = nil,
        hostRealtimeRequiredBitrateForQualityBps: Int? = nil,
        hostRealtimeObservedPFrameWireBytesP95: Int? = nil,
        hostRealtimeFrameBudgetBytes: Int? = nil,
        hostRealtimeFrameBudgetBitrateBps: Int? = nil,
        hostAwdlPolicyState: String? = nil,
        hostAwdlPolicyTrigger: String? = nil,
        hostAwdlSelectedLever: String? = nil,
        hostAwdlPlayoutDelayMs: Double? = nil,
        hostAwdlResolutionScale: Double? = nil,
        hostAwdlQualityReductionAllowed: Bool? = nil,
        hostAwdlPacingBudgetBps: Int? = nil,
        hostCaptureAdmissionDrops: UInt64? = nil,
        hostTransportAdmissionSkips: UInt64? = nil,
        hostTransportAdmissionMode: String? = nil,
        hostTransportAdmissionReason: String? = nil,
        hostTransportAdmissionEvidence: String? = nil,
        hostTransportAdmissionMinimumFrameIntervalMs: Double? = nil,
        hostTransportAdmissionActiveHoldMs: Double? = nil,
        hostTransportAdmissionSkipBurstCount: UInt64? = nil,
        hostHighRefreshPacingSkips: UInt64? = nil,
        hostHighRefreshPacingMode: String? = nil,
        hostHighRefreshPacingReason: String? = nil,
        hostHighRefreshPacingFloorFPS: Int? = nil,
        hostReadabilityProtectionSkips: UInt64? = nil,
        hostReadabilityProtectionMode: String? = nil,
        hostReadabilityProtectionReason: String? = nil,
        hostReadabilityProtectionAdmitTargetFPS: Int? = nil,
        hostRuntimeQualityFloor: Double? = nil,
        hostRuntimeQualityCeiling: Double? = nil,
        hostFrameBudgetMs: Double? = nil,
        hostAverageEncodeMs: Double? = nil,
        hostCaptureIngressFPS: Double? = nil,
        hostCaptureFPS: Double? = nil,
        hostEncodeAttemptFPS: Double? = nil,
        hostUsingHardwareEncoder: Bool? = nil,
        hostEncoderGPURegistryID: UInt64? = nil,
        hostEncodedWidth: Int? = nil,
        hostEncodedHeight: Int? = nil,
        hostCapturePixelFormat: String? = nil,
        hostCaptureColorPrimaries: String? = nil,
        hostEncoderPixelFormat: String? = nil,
        hostEncoderChromaSampling: String? = nil,
        hostEncoderProfile: String? = nil,
        hostEncoderColorPrimaries: String? = nil,
        hostEncoderTransferFunction: String? = nil,
        hostEncoderYCbCrMatrix: String? = nil,
        hostDisplayP3CoverageStatus: MirageMedia.MirageDisplayP3CoverageStatus? = nil,
        hostTenBitDisplayP3Validated: Bool? = nil,
        hostUltra444Validated: Bool? = nil,
        clientDecoderOutputPixelFormat: String? = nil,
        clientUsingHardwareDecoder: Bool? = nil,
        hasHostMetrics: Bool = false
    ) {
        self.decodedFPS = decodedFPS
        self.receivedFPS = receivedFPS
        self.clientReceivedWorstGapMs = clientReceivedWorstGapMs
        self.clientReceivedFrameIntervalP95Ms = clientReceivedFrameIntervalP95Ms
        self.clientReceivedFrameIntervalP99Ms = clientReceivedFrameIntervalP99Ms
        self.clientReceiverIngressJitterP95Ms = max(0, clientReceiverIngressJitterP95Ms)
        self.clientReceiverIngressJitterP99Ms = max(0, clientReceiverIngressJitterP99Ms)
        self.clientDisplayTickFPS = clientDisplayTickFPS
        self.clientSubmitAttemptFPS = clientSubmitAttemptFPS
        self.clientLayerAcceptedFPS = clientLayerAcceptedFPS
        self.clientPresentedFPS = clientPresentedFPS
        self.submittedFPS = submittedFPS
        self.uniqueSubmittedFPS = uniqueSubmittedFPS
        self.pendingFrameCount = pendingFrameCount
        self.clientPendingFrameAgeMs = clientPendingFrameAgeMs
        self.clientSmoothestDisplayDebtMs = max(0, clientSmoothestDisplayDebtMs)
        self.clientSmoothestDisplayDebtCapMs = max(0, clientSmoothestDisplayDebtCapMs)
        self.clientSmoothestTargetDelayMs = max(0, clientSmoothestTargetDelayMs)
        self.clientSmoothestUnderflowCount = clientSmoothestUnderflowCount
        self.clientOverwrittenPendingFrames = clientOverwrittenPendingFrames
        self.clientSmoothestQueueDrops = clientSmoothestQueueDrops
        self.clientSmoothestDisplayDebtDrops = clientSmoothestDisplayDebtDrops
        self.clientSmoothestFifoResetCount = clientSmoothestFifoResetCount
        self.clientSmoothestDepthDrops = clientSmoothestDepthDrops
        self.clientSmoothestAgeDrops = clientSmoothestAgeDrops
        self.clientSmoothestDropsUnder100ms = clientSmoothestDropsUnder100ms
        self.clientSmoothestDroppedFrameAgeMaxMs = clientSmoothestDroppedFrameAgeMaxMs
        self.clientLateFrameDrops = clientLateFrameDrops
        self.clientDisplayLayerNotReadyCount = clientDisplayLayerNotReadyCount
        self.clientPendingFrameNotReadyDisplayTickCount = clientPendingFrameNotReadyDisplayTickCount
        self.clientRepeatedFrameCount = clientRepeatedFrameCount
        clientRepeatedDeliveredSourceFrameCount = 0
        self.clientMissedVSyncCount = clientMissedVSyncCount
        self.clientDisplayTickIntervalP95Ms = clientDisplayTickIntervalP95Ms
        self.clientDisplayTickIntervalP99Ms = clientDisplayTickIntervalP99Ms
        self.clientPlayoutDelayFrames = clientPlayoutDelayFrames
        self.clientPresentationStallCount = clientPresentationStallCount
        self.clientWorstPresentationGapMs = clientWorstPresentationGapMs
        self.clientFrameIntervalP95Ms = clientFrameIntervalP95Ms
        self.clientFrameIntervalP99Ms = clientFrameIntervalP99Ms
        self.decodeHealthy = decodeHealthy
        self.clientDroppedFrames = clientDroppedFrames
        self.clientReassemblerPendingFrameCount = clientReassemblerPendingFrameCount
        self.clientReassemblerPendingKeyframeCount = clientReassemblerPendingKeyframeCount
        self.clientReassemblerPendingBytes = clientReassemblerPendingBytes
        self.clientFrameBufferPoolRetainedBytes = clientFrameBufferPoolRetainedBytes
        self.clientReassemblerBudgetEvictions = clientReassemblerBudgetEvictions
        self.clientReassemblerIncompleteFrameTimeouts = clientReassemblerIncompleteFrameTimeouts
        self.clientReassemblerIncompleteFrameNoProgressTimeouts = clientReassemblerIncompleteFrameNoProgressTimeouts
        self.clientReassemblerIncompleteFrameLifetimeTimeouts = clientReassemblerIncompleteFrameLifetimeTimeouts
        self.clientReassemblerMissingFragmentTimeouts = clientReassemblerMissingFragmentTimeouts
        self.clientReassemblerForwardGapTimeouts = clientReassemblerForwardGapTimeouts
        self.clientFrameCompletionLatencyP50Ms = max(0, clientFrameCompletionLatencyP50Ms)
        self.clientFrameCompletionLatencyP95Ms = max(0, clientFrameCompletionLatencyP95Ms)
        self.clientFrameCompletionLatencyMaxMs = max(0, clientFrameCompletionLatencyMaxMs)
        self.clientKeyframeCompletionLatencyP50Ms = max(0, clientKeyframeCompletionLatencyP50Ms)
        self.clientKeyframeCompletionLatencyP95Ms = max(0, clientKeyframeCompletionLatencyP95Ms)
        self.clientKeyframeCompletionLatencyMaxMs = max(0, clientKeyframeCompletionLatencyMaxMs)
        self.clientPFrameCompletionLatencyP50Ms = max(0, clientPFrameCompletionLatencyP50Ms)
        self.clientPFrameCompletionLatencyP95Ms = max(0, clientPFrameCompletionLatencyP95Ms)
        self.clientPFrameCompletionLatencyMaxMs = max(0, clientPFrameCompletionLatencyMaxMs)
        self.clientLatePFrameCompletionCount = clientLatePFrameCompletionCount
        self.clientReassemblerFECRecoveredFragmentCount = clientReassemblerFECRecoveredFragmentCount
        clientDecodeBacklogFrameCount = 0
        self.hostEncodedFPS = hostEncodedFPS
        self.hostIdleFPS = hostIdleFPS
        self.hostDroppedFrames = hostDroppedFrames
        self.hostActiveQuality = hostActiveQuality
        self.hostLatestAppliedFrameQuality = hostLatestAppliedFrameQuality
        self.hostLatestAppliedFrameBitrateTargetBps = hostLatestAppliedFrameBitrateTargetBps
        self.hostLatestAppliedFrameSenderPacingBps = hostLatestAppliedFrameSenderPacingBps
        self.hostLatestAppliedFrameIntent = hostLatestAppliedFrameIntent
        self.hostLatestAppliedFrameRate = hostLatestAppliedFrameRate
        self.hostTargetFrameRate = hostTargetFrameRate
        self.hostEnteredBitrate = hostEnteredBitrate
        self.hostCurrentBitrate = hostCurrentBitrate
        self.hostEncoderRequestedBitrateBps = hostEncoderRequestedBitrateBps
        self.hostEncoderActualBitrateBps = hostEncoderActualBitrateBps
        self.hostEncoderActualWindowMs = hostEncoderActualWindowMs
        self.hostEncodedFrameBytesP50 = hostEncodedFrameBytesP50
        self.hostEncodedFrameBytesP95 = hostEncodedFrameBytesP95
        self.hostEncodedFrameBytesP99 = hostEncodedFrameBytesP99
        self.hostEncodedKeyframeBytesP50 = hostEncodedKeyframeBytesP50
        self.hostEncodedKeyframeBytesP95 = hostEncodedKeyframeBytesP95
        self.hostEncodedKeyframeBytesP99 = hostEncodedKeyframeBytesP99
        self.hostEncoderRateControlStrategy = hostEncoderRateControlStrategy
        self.hostEncoderRateLimitBytes = hostEncoderRateLimitBytes
        self.hostEncoderRateLimitWindowMs = hostEncoderRateLimitWindowMs
        self.hostEffectiveStreamScale = hostEffectiveStreamScale
        self.hostAdaptiveStreamScaleReason = hostAdaptiveStreamScaleReason
        self.hostEncoderRetuneValidationResult = hostEncoderRetuneValidationResult
        self.hostEncoderKeyframeForRetuneCount = hostEncoderKeyframeForRetuneCount
        self.hostEncoderSessionRecreationCount = hostEncoderSessionRecreationCount
        self.hostRequestedTargetBitrate = hostRequestedTargetBitrate
        self.hostBitrateAdaptationCeiling = hostBitrateAdaptationCeiling
        self.hostStartupBitrate = hostStartupBitrate
        self.hostRealtimeBitrateCeiling = hostRealtimeBitrateCeiling
        self.hostRealtimePressureState = hostRealtimePressureState
        self.hostRealtimeControlRevision = hostRealtimeControlRevision
        self.hostAdaptiveGovernorRevision = hostAdaptiveGovernorRevision
        self.hostAdaptiveGovernorDecisionID = hostAdaptiveGovernorDecisionID
        self.hostAdaptiveGovernorState = hostAdaptiveGovernorState
        self.hostAdaptiveGovernorEvidenceClass = hostAdaptiveGovernorEvidenceClass
        self.hostAdaptiveGovernorCause = hostAdaptiveGovernorCause
        self.hostAdaptiveGovernorSelectedLever = hostAdaptiveGovernorSelectedLever
        self.hostAdaptiveGovernorBlockedLeverReason = hostAdaptiveGovernorBlockedLeverReason
        self.hostAdaptiveGovernorEvidenceSummary = hostAdaptiveGovernorEvidenceSummary
        self.hostRealtimePressureReason = hostRealtimePressureReason
        self.hostRealtimeDeliveryMode = hostRealtimeDeliveryMode
        self.hostRealtimeRequiredBitrateForQualityBps = hostRealtimeRequiredBitrateForQualityBps
        self.hostRealtimeObservedPFrameWireBytesP95 = hostRealtimeObservedPFrameWireBytesP95
        self.hostRealtimeFrameBudgetBytes = hostRealtimeFrameBudgetBytes
        self.hostRealtimeFrameBudgetBitrateBps = hostRealtimeFrameBudgetBitrateBps
        self.hostAwdlPolicyState = hostAwdlPolicyState
        self.hostAwdlPolicyTrigger = hostAwdlPolicyTrigger
        self.hostAwdlSelectedLever = hostAwdlSelectedLever
        self.hostAwdlPlayoutDelayMs = hostAwdlPlayoutDelayMs
        self.hostAwdlResolutionScale = hostAwdlResolutionScale
        self.hostAwdlQualityReductionAllowed = hostAwdlQualityReductionAllowed
        self.hostAwdlPacingBudgetBps = hostAwdlPacingBudgetBps
        self.hostCaptureAdmissionDrops = hostCaptureAdmissionDrops
        self.hostTransportAdmissionSkips = hostTransportAdmissionSkips
        self.hostTransportAdmissionMode = hostTransportAdmissionMode
        self.hostTransportAdmissionReason = hostTransportAdmissionReason
        self.hostTransportAdmissionEvidence = hostTransportAdmissionEvidence
        self.hostTransportAdmissionMinimumFrameIntervalMs = hostTransportAdmissionMinimumFrameIntervalMs
        self.hostTransportAdmissionActiveHoldMs = hostTransportAdmissionActiveHoldMs
        self.hostTransportAdmissionSkipBurstCount = hostTransportAdmissionSkipBurstCount
        self.hostHighRefreshPacingSkips = hostHighRefreshPacingSkips
        self.hostHighRefreshPacingMode = hostHighRefreshPacingMode
        self.hostHighRefreshPacingReason = hostHighRefreshPacingReason
        self.hostHighRefreshPacingFloorFPS = hostHighRefreshPacingFloorFPS
        self.hostReadabilityProtectionSkips = hostReadabilityProtectionSkips
        self.hostReadabilityProtectionMode = hostReadabilityProtectionMode
        self.hostReadabilityProtectionReason = hostReadabilityProtectionReason
        self.hostReadabilityProtectionAdmitTargetFPS = hostReadabilityProtectionAdmitTargetFPS
        self.hostRuntimeQualityFloor = hostRuntimeQualityFloor
        self.hostRuntimeQualityCeiling = hostRuntimeQualityCeiling
        self.hostFrameBudgetMs = hostFrameBudgetMs
        self.hostAverageEncodeMs = hostAverageEncodeMs
        self.hostCaptureIngressFPS = hostCaptureIngressFPS
        self.hostCaptureFPS = hostCaptureFPS
        self.hostEncodeAttemptFPS = hostEncodeAttemptFPS
        self.hostUsingHardwareEncoder = hostUsingHardwareEncoder
        self.hostEncoderGPURegistryID = hostEncoderGPURegistryID
        self.hostEncodedWidth = hostEncodedWidth
        self.hostEncodedHeight = hostEncodedHeight
        self.hostCapturePixelFormat = hostCapturePixelFormat
        self.hostCaptureColorPrimaries = hostCaptureColorPrimaries
        self.hostEncoderPixelFormat = hostEncoderPixelFormat
        self.hostEncoderChromaSampling = hostEncoderChromaSampling
        self.hostEncoderProfile = hostEncoderProfile
        self.hostEncoderColorPrimaries = hostEncoderColorPrimaries
        self.hostEncoderTransferFunction = hostEncoderTransferFunction
        self.hostEncoderYCbCrMatrix = hostEncoderYCbCrMatrix
        self.hostDisplayP3CoverageStatus = hostDisplayP3CoverageStatus
        self.hostTenBitDisplayP3Validated = hostTenBitDisplayP3Validated
        self.hostUltra444Validated = hostUltra444Validated
        self.clientDecoderOutputPixelFormat = clientDecoderOutputPixelFormat
        self.clientUsingHardwareDecoder = clientUsingHardwareDecoder
        hostSCKSampleDurationSeconds = nil
        hostRawScreenCallbackFPS = nil
        hostCompleteFrameFPS = nil
        hostRenderableFrameFPS = nil
        hostCadenceAdmittedFrameFPS = nil
        hostObservedSCKFPS = nil
        hostRawScreenCallbackCount = nil
        hostCompleteFrameCount = nil
        hostRenderableFrameCount = nil
        hostIdleFrameCount = nil
        hostCadenceAdmittedFrameCount = nil
        hostMediaMaxPacketSize = nil
        hostMediaSendProfile = nil
        hostStalePacketDrops = nil
        hostSenderLocalDeadlineDrops = nil
        hostGenerationAbortDrops = nil
        hostNonKeyframeHoldDrops = nil
        hostQueuedUnreliableDropCounts = nil
        hostQueuedUnreliablePendingPackets = nil
        hostQueuedUnreliableOutstandingPackets = nil
        hostQueuedUnreliableQueuedBytes = nil
        hostQueuedUnreliablePendingPacketMax = nil
        hostQueuedUnreliableOutstandingPacketMax = nil
        hostQueuedUnreliableQueuedBytesMax = nil
        hostQueuedUnreliableEnqueuedCount = nil
        hostQueuedUnreliableSentCount = nil
        hostQueuedUnreliableCompletedCount = nil
        hostQueuedUnreliableDroppedCount = nil
        hostQueuedUnreliableErrorCount = nil
        hostQueuedUnreliableQueueDwellP50Ms = nil
        hostQueuedUnreliableQueueDwellP95Ms = nil
        hostQueuedUnreliableQueueDwellP99Ms = nil
        hostQueuedUnreliableSendGapP50Ms = nil
        hostQueuedUnreliableSendGapP95Ms = nil
        hostQueuedUnreliableSendGapP99Ms = nil
        hostQueuedUnreliableContentProcessedP50Ms = nil
        hostQueuedUnreliableContentProcessedP95Ms = nil
        hostQueuedUnreliableContentProcessedP99Ms = nil
        self.hasHostMetrics = hasHostMetrics
    }
}
