//
//  MessageTypes+SupportLogs.swift
//  MirageKit
//
//  Created by Ethan Lipnik on 3/13/26.
//
//  Support log export request/response messages.
//

import Foundation
import Loom

/// Request a zipped support log archive from the connected host (Client -> Host).
package struct HostSupportLogArchiveRequestMessage: Codable {
    package let requestID: UUID

    package init(requestID: UUID) {
        self.requestID = requestID
    }
}

/// Host support log archive transfer session bootstrap response (Host -> Client).
package struct HostSupportLogArchiveMessage: Codable {
    /// Request identifier generated by the client and echoed by the host.
    package let requestID: UUID?
    /// Suggested archive filename, including extension.
    package let fileName: String?
    /// Transport accepted by the dedicated Loom transfer listener.
    package let transportKind: LoomTransportKind?
    /// Port bound by the dedicated Loom transfer listener.
    package let port: UInt16?
    /// Human-readable failure reason when archive creation was unsuccessful.
    package let errorMessage: String?

    package init(
        requestID: UUID? = nil,
        fileName: String? = nil,
        transportKind: LoomTransportKind? = nil,
        port: UInt16? = nil,
        errorMessage: String? = nil
    ) {
        self.requestID = requestID
        self.fileName = fileName
        self.transportKind = transportKind
        self.port = port
        self.errorMessage = errorMessage
    }
}
